### ISSUE TITLE
incorrect sigmoid

### ISSUE THREAD

**Issue by harishthedelhichaiwalah** [Parthiee/Machine-Learning-in-C#1]
hey creator

The code fails to properly define the sigmoid function, likely missing the exponential term needed for 1/(1+e^-x) representation. This omission results in an inaccurate activation function, crucial for neural network training, hindering its ability to model non-linear relationships. please consider the change

**Comment by Parthiee** [comment]
Hey there! 
I had a look at the function definition and it seems fine to me. I have used the exp() of math.h to account for the exponential function. If you are referring to someother error, can you give me the precise filename where the incorrect definition is?


![Screenshot_2023-12-09-12-20-28-95_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/Parthiee/Neural-Network-in-C/assets/100670393/35d2b57a-cb96-43d6-8836-64ee212a98bf)

**Comment by harishthedelhichaiwalah** [comment]
why have you used C ?

**Comment by harishthedelhichaiwalah** [comment]
How can you close the issue without addressing it.

**Comment by harishthedelhichaiwalah** [comment]
this is github sir. not pornhub
